// =====================================================================
//  Showreel asset  --  the player's ship (see player_ship.h)
// =====================================================================

#include "assets/player_ship.h"
#include <stdio.h>
#include "assets/flame.h"
#include "esp_log.h"
#include "mesh.h"
#include "mesh_render.h"
#include "objects/ship_model.h"

static char const TAG[] = "player_ship";

// --- Normalising the raw model ------------------------------------------
//
// Lateral extent of the raw model, in model units (x spans -5.75..5.75).
// From the mesh, not a free parameter: re-export the 3MF wider and this
// is what has to change for "wingspan = 1" to still hold.
#define RAW_SPAN  11.5f
// The raw model is centred in x and z but base-anchored in y (belly at
// y = 0, roof at 2.949); the normalised model is centred on mid-height.
#define RAW_MID_Y 1.474519f

static vec3_t normalise(float x, float y, float z) {
    return v3(x / RAW_SPAN, (y - RAW_MID_Y) / RAW_SPAN, z / RAW_SPAN);
}

// --- Hull plates --------------------------------------------------------
//
// The gold hull (SHIP_REGION_BODY) is textured with bare-metal plates
// (textures/, generated by tools/make_textures.py). The mesh is a single
// connected surface, so its "parts" are drawn from where each face sits
// and which way it points, in raw model space:
//
//   fuselage   face centroid within |x| < 1.6 -- the central body and
//              the pointed nose (lateral extent -1.5..1.5)
//   pod        |x| >= 4.2 -- the two outer nacelles (4.25..5.75)
//   wing       everything laterally in between
//   belly      any face pointing mostly down (normal y < -0.7), whatever
//              part it belongs to -- the underside reads as one armoured
//              skin rather than three different metals
typedef enum {
    PLATE_FUSELAGE = 0,
    PLATE_WING,
    PLATE_POD,
    PLATE_BELLY,
    PLATE_COUNT,
} plate_t;

static char const* const PLATE_FILES[PLATE_COUNT] = {
    [PLATE_FUSELAGE] = "plate_riveted.png",
    [PLATE_WING]     = "plate_brushed.png",
    [PLATE_POD]      = "plate_gunmetal.png",
    [PLATE_BELLY]    = "plate_tread.png",
};

#define PLATE_FUSELAGE_MAX_X 1.6f  // raw model units
#define PLATE_POD_MIN_X      4.2f
#define PLATE_BELLY_NY       (-0.7f)
// Raw model units covered by one repeat of a 64-texel plate. At the
// turntable's framing a raw unit is ~29 px, so 2.5 units puts a texel at
// ~1.1 px: just magnified, which keeps nearest-texel sampling from
// shimmering as the hull turns. Smaller repeats alias; larger ones get
// blocky up close.
#define PLATE_REPEAT         2.5f

// Materials: the four plates, then one flat colour per model region.
#define MAT_REGION0 PLATE_COUNT
#define MAT_COUNT   (PLATE_COUNT + SHIP_REGION_COUNT)

// Textures stay in PSRAM for now (see devdocs/performance.md).
#define PLATE_TEXTURE_FLAGS 0

// --- Flames ---------------------------------------------------------------
//
// The engine pods are hexagonal prisms (circumradius 0.75, centred at
// x = +-5.0, y = 1.299) whose rear faces lie in the rearmost plane,
// z = -5.125. Each flame's base is a hexagon on that face, inset to
// NOZZLE_R so a rim of pod shows round it.
#define POD_X       5.0f  // raw units, +- for the two pods
#define POD_Y       1.299038f
#define POD_REAR_Z  (-5.125f)
#define NOZZLE_R    0.6f
#define FLAME_LEN   3.0f   // nominal, raw units; flicker scales it
#define FLICKER_TOP 1.10f  // flame.c's FLICKER_MAX, for framing

// The ridge outline (SHIP_MODEL_EDGES), drawn over the faces. Off: the
// textured plates carry their own seams and panel lines. Set to 1 to
// bring it back; nothing else depends on it.
#define DRAW_OUTLINE 0

static mesh_t        s_mesh;
static mesh_mat_t    s_mats[MAT_COUNT];
static se_texture_t* s_plate_tex[PLATE_COUNT];
static bool          s_ready;

static plate_t classify(ship_model_tri_t const* t, vec3_t n) {
    ship_model_vert_t const* a  = &SHIP_MODEL_VERTS[t->a];
    ship_model_vert_t const* b  = &SHIP_MODEL_VERTS[t->b];
    ship_model_vert_t const* c  = &SHIP_MODEL_VERTS[t->c];
    float const              cx = fabsf((a->x + b->x + c->x) * (1.0f / 3.0f));
    if (n.y < PLATE_BELLY_NY) return PLATE_BELLY;
    if (cx < PLATE_FUSELAGE_MAX_X) return PLATE_FUSELAGE;
    if (cx >= PLATE_POD_MIN_X) return PLATE_POD;
    return PLATE_WING;
}

// Planar ("box") mapping per face, in raw units: project the face onto
// whichever axis plane it faces most squarely, so the plate lies flat
// on it with no stretching. Neighbouring faces that pick different
// planes meet at a seam in the pattern, which reads as a panel join.
static void plate_uv(ship_model_tri_t const* t, vec3_t n, float uv[3][2]) {
    int const   idx[3] = {t->a, t->b, t->c};
    float const ax = fabsf(n.x), ay = fabsf(n.y), az = fabsf(n.z);
    for (int k = 0; k < 3; k++) {
        ship_model_vert_t const* v = &SHIP_MODEL_VERTS[idx[k]];
        float                    u, w;
        if (ay >= ax && ay >= az) {  // top / bottom: lay the plate on x-z
            u = v->x;
            w = v->z;
        } else if (ax >= az) {  // sides: z along, y down the texture
            u = v->z;
            w = -v->y;
        } else {  // front / back: x along, y down
            u = v->x;
            w = -v->y;
        }
        uv[k][0] = u / PLATE_REPEAT;
        uv[k][1] = w / PLATE_REPEAT;
    }
}

static void build_mesh(void) {
    mesh_init(&s_mesh);
    for (size_t i = 0; i < SHIP_MODEL_VERT_COUNT; i++) {
        ship_model_vert_t const* v = &SHIP_MODEL_VERTS[i];
        mesh_vert(&s_mesh, normalise(v->x, v->y, v->z));
    }
    for (size_t i = 0; i < SHIP_MODEL_TRI_COUNT; i++) {
        ship_model_tri_t const* t        = &SHIP_MODEL_TRIS[i];
        float                   uv[3][2] = {{0}};
        uint8_t                 mat      = (uint8_t)(MAT_REGION0 + t->region);
        if (t->region == SHIP_REGION_BODY) {
            ship_model_vert_t const* a = &SHIP_MODEL_VERTS[t->a];
            ship_model_vert_t const* b = &SHIP_MODEL_VERTS[t->b];
            ship_model_vert_t const* c = &SHIP_MODEL_VERTS[t->c];
            vec3_t const             n =
                v3_norm(v3_cross(v3(b->x - a->x, b->y - a->y, b->z - a->z), v3(c->x - a->x, c->y - a->y, c->z - a->z)));
            mat = (uint8_t)classify(t, n);
            plate_uv(t, n, uv);
        }
        mesh_tri(&s_mesh, t->a, t->b, t->c, mat, uv);
    }
    if (s_mesh.failed) ESP_LOGE(TAG, "out of memory building the hull mesh");
}

int player_ship_init(char const* asset_dir) {
    if (s_ready) return PLATE_COUNT;
    build_mesh();
    flame_init(asset_dir);

    int loaded = 0;
    for (int p = 0; p < PLATE_COUNT; p++) {
        char path[256];
        snprintf(path, sizeof(path), "%s/%s", asset_dir ? asset_dir : ".", PLATE_FILES[p]);
        s_plate_tex[p] = se_texture_load(path, PLATE_TEXTURE_FLAGS);
        if (s_plate_tex[p] != NULL) {
            loaded++;
        } else {
            ESP_LOGW(TAG, "%s missing -- those faces stay gold", PLATE_FILES[p]);
        }
        // A plate that failed to load draws flat, in the gold it replaces.
        s_mats[p] = (mesh_mat_t){s_plate_tex[p], SHIP_REGION_COLOR[SHIP_REGION_BODY], 0};
    }
    // Every region is drawn: the racer hides the battery panel and the
    // magnet poles until those attachments are fitted, but a showreel
    // wants the fully equipped ship.
    for (int r = 0; r < SHIP_REGION_COUNT; r++) {
        s_mats[MAT_REGION0 + r] = (mesh_mat_t){NULL, SHIP_REGION_COLOR[r], 0};
    }
    s_ready = true;
    return loaded;
}

void player_ship_shutdown(void) {
    for (int p = 0; p < PLATE_COUNT; p++) {
        se_texture_unload(s_plate_tex[p]);
        s_plate_tex[p] = NULL;
    }
    flame_shutdown();
    mesh_free(&s_mesh);
    s_ready = false;
}

void player_ship_submit(xform_t const* x, float throttle, double t) {
    if (!s_ready) return;
    mesh_submit(&s_mesh, x, s_mats, MAT_COUNT);

    if (throttle > 0.0f) {
        vec3_t const left  = normalise(-POD_X, POD_Y, POD_REAR_Z);
        vec3_t const right = normalise(POD_X, POD_Y, POD_REAR_Z);
        float const  len   = FLAME_LEN / RAW_SPAN * throttle;
        flame_submit(x, left, NOZZLE_R / RAW_SPAN, len * flame_flicker(t, 1u), FLAME_BLUE);
        flame_submit(x, right, NOZZLE_R / RAW_SPAN, len * flame_flicker(t, 2u), FLAME_BLUE);
    }

#if DRAW_OUTLINE
    // scene_rasterize biases edges towards the camera, so an edge wins
    // against the face it outlines but still loses to nearer geometry.
    vec3_t const* w = mesh_last_world();
    for (size_t i = 0; i < SHIP_MODEL_EDGE_COUNT; i++) {
        vec3_t const a = w[SHIP_MODEL_EDGES[i][0]], b = w[SHIP_MODEL_EDGES[i][1]];
        scene_line(a.x, a.y, a.z, b.x, b.y, b.z, SHIP_MODEL_OUTLINE_COLOR);
    }
#endif
}

void player_ship_bounds(vec3_t* lo, vec3_t* hi) {
    vec3_t l = v3(1e9f, 1e9f, 1e9f), h = v3(-1e9f, -1e9f, -1e9f);
    for (size_t i = 0; i < SHIP_MODEL_VERT_COUNT; i++) {
        vec3_t const p = normalise(SHIP_MODEL_VERTS[i].x, SHIP_MODEL_VERTS[i].y, SHIP_MODEL_VERTS[i].z);
        l              = v3(fminf(l.x, p.x), fminf(l.y, p.y), fminf(l.z, p.z));
        h              = v3(fmaxf(h.x, p.x), fmaxf(h.y, p.y), fmaxf(h.z, p.z));
    }
    if (lo) *lo = l;
    if (hi) *hi = h;
}

float player_ship_flame_reach(void) {
    return FLAME_LEN * FLICKER_TOP / RAW_SPAN;
}
