PORT ?= /dev/ttyACM0
BADGELINKPORT ?= $(PORT)

SHELL := /usr/bin/env bash

# App installation settings
APP_SLUG_NAME ?= at.cavac.showreel
APP_INSTALL_BASE_PATH ?= /sd/apps/
APP_INSTALL_PATH = $(APP_INSTALL_BASE_PATH)$(APP_SLUG_NAME)

# The reel's segments: each has its code in main/<segment>/ and its
# textures in textures/<segment>/ (generated by tools/make_textures.py).
# The textures are installed in the same subdirectories next to app.so;
# the app finds them through graceloader_get_install_basepath().
SEGMENTS := space craftminer
TEXTURES := $(patsubst textures/%,%,$(wildcard $(addprefix textures/,$(addsuffix /*.png,$(SEGMENTS)))))

# ESP-IDF tools path (needed for the RISC-V cross-compiler)
IDF_PATH ?= $(shell cat .IDF_PATH 2>/dev/null || echo `pwd`/esp-idf)
IDF_TOOLS_PATH ?= $(shell cat .IDF_TOOLS_PATH 2>/dev/null || echo `pwd`/esp-idf-tools)
IDF_VERSION ?= v6.0.2
IDF_GITHUB_ASSETS ?= dl.espressif.com/github_assets

# The ESP-IDF environment script. Only mode_badgelink needs it (for pyserial
# out of the IDF python env -- the app build itself just needs the toolchain
# via IDF_TOOLS_PATH). Honours an IDF_SOURCE already exported by the shell.
IDF_SOURCE ?= $(shell cat .IDF_PATH 2>/dev/null && echo '$(IDF_PATH)/export.sh' || test -d `pwd`/esp-idf && echo '$(IDF_PATH)/export.sh' || echo '$(HOME)/.espressif/tools/activate_idf_$(IDF_VERSION).sh')

export IDF_TOOLS_PATH
export IDF_GITHUB_ASSETS

BUILD ?= build

MAKEFLAGS += --silent

####

.PHONY: all
all: build

.PHONY: build
build:
	python3 tools/segcheck.py $(SEGMENTS)
	@echo "=== Building app.so ==="
	mkdir -p $(BUILD)
	cd $(BUILD) && cmake $(CMAKE_FLAGS) .. && make
	@echo "=== Build complete: $(BUILD)/app.so ==="

# Badgelink
.PHONY: badgelink
badgelink:
	rm -rf badgelink
	#git clone https://github.com/badgeteam/esp32-component-badgelink.git badgelink
	git clone https:///github.com/nullislandspace/esp32-component-badgelink.git badgelink
	cd badgelink/tools; ./install.sh

# Determine badgelink connection argument: --tcp for host:port, --port for serial devices
BADGELINK_CONN := $(if $(findstring :,$(BADGELINKPORT)),--tcp $(BADGELINKPORT),--port $(BADGELINKPORT))

# Every badgelink call goes through a retry wrapper: a fresh connection
# intermittently fails with "Invalid sync" when the TCP proxy still holds
# bytes from a previous session (from tanmatsu-idf6tests).
BADGELINK := tools/badgelink_retry.sh $(BADGELINK_CONN)

# Needs BadgeLink mode, which mode_badgelink sets up (and which also gets a
# still-running showreel out of the way first).
.PHONY: install
install: build mode_badgelink
	@echo "=== Installing to device ==="
	@echo "Creating directory $(APP_INSTALL_PATH)..."
	badgelink/tools/badgelink.sh $(BADGELINK_CONN) fs mkdir $(APP_INSTALL_PATH) >/dev/null 2>&1 || true
	@echo "Uploading metadata.json and icons..."
	$(BADGELINK) fs upload $(APP_INSTALL_PATH)/metadata.json metadata/metadata.json
	$(BADGELINK) fs upload $(APP_INSTALL_PATH)/icon16.png metadata/icon16.png
	$(BADGELINK) fs upload $(APP_INSTALL_PATH)/icon32.png metadata/icon32.png
	$(BADGELINK) fs upload $(APP_INSTALL_PATH)/icon64.png metadata/icon64.png
	@echo "Uploading app.so..."
	$(BADGELINK) fs upload $(APP_INSTALL_PATH)/app.so $(BUILD)/app.so
	# (no retries: once the directories exist, mkdir fails, as it should)
	for s in $(SEGMENTS); do badgelink/tools/badgelink.sh $(BADGELINK_CONN) fs mkdir $(APP_INSTALL_PATH)/$$s >/dev/null 2>&1 || true; done
	for t in $(TEXTURES); do \
	  echo "Uploading $$t..."; \
	  $(BADGELINK) fs upload $(APP_INSTALL_PATH)/$$t textures/$$t || exit 1; \
	done
	@echo "=== Installation complete ==="

GRACELOADER_SLUG ?= at.cavac.graceloader

.PHONY: run
run: mode_badgelink
	$(BADGELINK) start $(GRACELOADER_SLUG) $(APP_INSTALL_PATH)/app.so

# USB mode switching
#
# The device's USB peripheral is in one of two modes: BadgeLink (USB_DEVICE),
# which is what install / run need, or flash-and-monitor (USB_DEBUG). After an
# app hands the badge back, the launcher is in debug mode.
#
# mode_badgelink asks for BadgeLink mode by sending "BADGELINK\n" on the debug
# console, then waits until BadgeLink actually answers. The launcher listens
# for it (../tanmatsu-launcher/main/usb_device.c); so does the showreel's own
# debug console (main/debugcon.h), which takes it as "exit to the launcher" --
# so the next attempt reaches the launcher. The request sometimes gets lost
# silently, so it is repeated. Does nothing if BadgeLink already answers, so
# other targets can depend on it. (After tanmatsu-idf6tests.)
#
# PORT accepts either a local device path (e.g. /dev/ttyACM0) or an rfc2217://
# URL pointing at ../tanmatsu-badgefs/rfc2217proxy when the device is
# forwarded over the network.
BADGELINK_SWITCH_TRIES ?= 6
BADGELINK_WAIT_TRIES ?= 5

.PHONY: mode_badgelink
mode_badgelink:
	if badgelink/tools/badgelink.sh $(BADGELINK_CONN) fs list /sd >/dev/null 2>&1; then \
		echo "Badge is already in BadgeLink mode"; exit 0; \
	fi; \
	source "$(IDF_SOURCE)" >/dev/null; \
	for s in $$(seq 1 $(BADGELINK_SWITCH_TRIES)); do \
		echo "Requesting BadgeLink mode on $(PORT) (attempt $$s)..."; \
		python3 -c "import serial, sys; s=serial.serial_for_url('$(PORT)', timeout=1); s.write(b'BADGELINK\n'); s.flush(); sys.stdout.write(s.read(128).decode(errors='replace')); s.close()" || true; \
		echo; \
		for i in $$(seq 1 $(BADGELINK_WAIT_TRIES)); do \
			sleep 1; \
			if badgelink/tools/badgelink.sh $(BADGELINK_CONN) fs list /sd >/dev/null 2>&1; then \
				echo "Badge is in BadgeLink mode"; exit 0; \
			fi; \
		done; \
	done; \
	echo "Timed out waiting for BadgeLink mode (a hung app? try 'make recover')" >&2; \
	exit 1

# Test automation (main/devtest.h, tools/testrun.py)
#
#   make testrun TEST="perf scene=turntable secs=20"      the app must be running
#   make cycle   TEST="shots scene=turntable ms=0,2500"   build, install, run, test
#   make testrefs    TEST="shots ..."                     cycle, then store the shot hashes as references
#   make testcompare TEST="shots ..."                     cycle, then compare the hashes against the references
#   make recover                                          after a crash or hang
#
# The app runs the test and returns to the launcher by itself; shot images
# stay on the SD card; TESTFLAGS=--fetch downloads them (slow).
TEST ?= perf scene=turntable secs=20
TESTFLAGS ?=

# MJPEG video export (main/export_mjpeg.h). Builds the export variant in
# its own build directory, installs it in place of the live reel and
# starts it: it renders every playlist scene once at a fixed 30 fps into
# /sd/showreel/showreel.avi (logging its progress on the console), then
# returns to the launcher. `make install` puts the live reel back.
# SEGMENT=<name> (one of SEGMENTS) exports that act on its own:
#   make export SEGMENT=craftminer
# Fetching the file over BadgeLink is slow (~18 KB/s, i.e. many minutes
# for a video of tens of MB); taking the SD card out is quicker:
#   badgelink/tools/badgelink.sh $(BADGELINK_CONN) fs download /sd/showreel/showreel.avi showreel.avi
.PHONY: export
export:
	$(MAKE) build install run BUILD=build-export \
	  CMAKE_FLAGS="-DSHOWREEL_EXPORT_MJPEG=ON -DSHOWREEL_SEGMENT=$(SEGMENT)"

.PHONY: testrun cycle testrefs testcompare recover
testrun:
	source "$(IDF_SOURCE)" >/dev/null && \
	python3 -u tools/testrun.py --port "$(PORT)" --badgelink-conn "$(BADGELINK_CONN)" $(TESTFLAGS) -- $(TEST)

cycle: build install run
	$(MAKE) testrun

testrefs:
	$(MAKE) cycle TESTFLAGS="--capture-refs"

testcompare:
	$(MAKE) cycle TESTFLAGS="--compare"

recover:
	source "$(IDF_SOURCE)" >/dev/null && python3 tools/recover.py --port "$(PORT)"

# The other direction: ask the firmware (in BadgeLink mode) to switch its USB
# back to flash/monitor mode, through BadgeLink's own `mode` command. Uses the
# badgelink checkout that `make badgelink` creates, and the same BADGELINK_CONN
# as install / run, so it follows a networked device too.
BADGELINK_SH := badgelink/tools/badgelink.sh

.PHONY: mode_debug
mode_debug:
	if [ ! -x "$(BADGELINK_SH)" ]; then \
	  echo "$(BADGELINK_SH) not found -- run 'make badgelink' first"; \
	  exit 1; \
	fi; \
	echo "Using $(BADGELINK_SH)"; \
	"$(BADGELINK_SH)" $(BADGELINK_CONN) mode debug

APP_REPO_PATH ?= ../tanmatsu-app-repository/$(APP_SLUG_NAME)

.PHONY: apprepo
apprepo: build
	@echo "=== Updating app repository ==="
	mkdir -p $(APP_REPO_PATH)
	cp metadata/metadata.json $(APP_REPO_PATH)/metadata.json
	cp metadata/icon16.png $(APP_REPO_PATH)/icon16.png
	cp metadata/icon32.png $(APP_REPO_PATH)/icon32.png
	cp metadata/icon64.png $(APP_REPO_PATH)/icon64.png
	cp $(BUILD)/app.so $(APP_REPO_PATH)/app.so
	for s in $(SEGMENTS); do mkdir -p $(APP_REPO_PATH)/$$s; done
	for t in $(TEXTURES); do cp textures/$$t $(APP_REPO_PATH)/$$t; done
	@echo "=== App repository updated at $(APP_REPO_PATH) ==="

# Preparation

.PHONY: prepare
prepare: sdk

.PHONY: sdk
sdk:
	if test -d "$(IDF_PATH)"; then echo -e "ESP-IDF target folder exists!\r\nPlease remove the folder or un-set the environment variable."; exit 1; fi
	if test -d "$(IDF_TOOLS_PATH)"; then echo -e "ESP-IDF tools target folder exists!\r\nPlease remove the folder or un-set the environment variable."; exit 1; fi
	git clone --recursive --branch "$(IDF_VERSION)" https://github.com/espressif/esp-idf.git "$(IDF_PATH)" --depth=1 --shallow-submodules
	cd "$(IDF_PATH)"; git submodule update --init --recursive
	cd "$(IDF_PATH)"; bash install.sh all

.PHONY: reinstallsdk
reinstallsdk:
	cd "$(IDF_PATH)"; bash install.sh all

.PHONY: removesdk
removesdk:
	rm -rf "$(IDF_PATH)"
	rm -rf "$(IDF_TOOLS_PATH)"

.PHONY: refreshsdk
refreshsdk: removesdk sdk

# Verification

.PHONY: verify
verify: build
	@echo "=== Verifying symbols ==="
	@MISSING=$$(comm -23 \
	  <(nm -D --undefined-only $(BUILD)/app.so | awk '{print $$2}' | sort -u) \
	  <(nm -D --defined-only fakelib/liball.so | awk '{print $$3}' | sort -u)); \
	if [ -n "$$MISSING" ]; then \
	  echo "ERROR: app.so requires symbols not in fakelib:"; \
	  echo "$$MISSING"; \
	  exit 1; \
	else \
	  echo "All symbols satisfied."; \
	fi

# Cleaning

.PHONY: clean
clean:
	rm -rf $(BUILD)

.PHONY: fullclean
fullclean: clean

# Formatting

# Regenerate textures/<segment>/*.png from tools/make_textures.py (needs numpy +
# Pillow). The PNGs are committed, so a normal build does not need this.
.PHONY: textures
textures:
	python3 tools/make_textures.py

# Host-side check of the math and every mesh generator (tools/meshcheck.c):
# closed, consistently wound, outward-facing parts; no badge needed. Asset
# generators that build meshes add their pure *_mesh.c file here.
HOSTCC ?= cc
MESHCHECK_SRCS := tools/meshcheck.c main/mesh.c main/xform.c \
                  main/space/assets/station_mesh.c main/space/assets/marauder_mesh.c \
                  main/space/assets/title_text_mesh.c main/space/assets/planet_base_mesh.c \
                  main/space/assets/asteroid_mesh.c main/craftminer/voxel/voxel_mesh.c \
                  main/craftminer/assets/miner_mesh.c

.PHONY: meshcheck
meshcheck:
	mkdir -p $(BUILD)/host
	$(HOSTCC) -O1 -Wall -Wextra -Werror=implicit-function-declaration -DMESH_HOST -Imain -Itools $(MESHCHECK_SRCS) -lm \
	  -o $(BUILD)/host/meshcheck
	$(BUILD)/host/meshcheck

# Host-side check of every scene (tools/scenecheck.c): runs the real scene
# and asset code at 30 fps against the engine's host harness
# (synthengine3D/host, see its docs/testing.md) and checks the near
# plane, list caps, clearances and framing. No badge needed.
# SCENES="name ..." checks only those; SCENECHECK_FLAGS=-v lists every
# clipped frame. mesh_render.c is built on its own, with its
# mesh_submit / mesh_submit_part renamed, so the checker can wrap them.
#
# The engine settings must match the app build or the checker compares
# frames against the wrong caps, so they are read straight out of
# CMakeLists.txt rather than written down twice.
ENGINE_DEFS := $(shell sed -n 's/^add_compile_definitions(\(SE_[A-Z_]*=[0-9]*\))/-D\1/p' CMakeLists.txt)
HOST_DIR    := synthengine3D/host
SCENECHECK_CFLAGS := -O2 -Wall -Wextra -Werror=implicit-function-declaration -DMESH_HOST \
                     -I$(HOST_DIR)/shims -I$(HOST_DIR) -Isynthengine3D/include -Itools -Imain $(ENGINE_DEFS)
SCENECHECK_SRCS   := tools/scenecheck.c $(HOST_DIR)/se_host_stub.c main/xform.c main/mesh.c main/camera.c main/horizon.c \
                     $(wildcard main/common/*.c main/dev/*.c) $(shell find $(addprefix main/,$(SEGMENTS)) -name '*.c')

.PHONY: scenecheck
scenecheck:
	mkdir -p $(BUILD)/host
	$(HOSTCC) $(SCENECHECK_CFLAGS) -Dmesh_submit=mesh_submit_real -Dmesh_submit_part=mesh_submit_part_real \
	  -c main/mesh_render.c -o $(BUILD)/host/mesh_render_real.o
	$(HOSTCC) $(SCENECHECK_CFLAGS) $(SCENECHECK_SRCS) $(BUILD)/host/mesh_render_real.o -lm -o $(BUILD)/host/scenecheck
	$(BUILD)/host/scenecheck $(SCENECHECK_FLAGS) $(SCENES)

# Keeps the segments apart (tools/segcheck.py, also run by every build):
# no includes or texture names across main/<segment>/ directories.
.PHONY: segcheck
segcheck:
	python3 tools/segcheck.py --self-test
	python3 tools/segcheck.py $(SEGMENTS)

.PHONY: format
format:
	find main/ \( -path main/third_party -o -path main/space/objects \) -prune -o \( -iname '*.h' -o -iname '*.c' -o -iname '*.cpp' \) -print | xargs clang-format -i
